<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eShop\eShop.CoreBusiness\eShop.CoreBusiness.csproj" />
    <ProjectReference Include="..\..\eShop\eShop.UseCases\eShop.UseCases.csproj" />
    <ProjectReference Include="..\..\eShop\eShop.Web.Modules\eShop.Web.CustomerPortal\eShop.Web.CustomerPortal.csproj" />
    <ProjectReference Include="..\..\eShop\Plugins\eShop.DataStore.HardCoded\eShop.DataStore.HardCoded.csproj" />
    <ProjectReference Include="..\..\eShop\Plugins\eShop.ShoppingCart.LocalStorage\eShop.ShoppingCart.LocalStorage.csproj" />
    <ProjectReference Include="..\..\eShop\Plugins\eShop.StateStore.DI\eShop.StateStore.DI.csproj" />
  </ItemGroup>

</Project>
